import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import Topnav from "./_components/Topnav";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <Topnav />
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
